# Mediation with Regression Analysis {#mediation}

### Test your intuition or knowledge {-}

```{r}
# TBD
```

## Mediation as Causal Process
{understanding the causal process in more detail ; conceptual diagram with paths of effects ; mediator variable (mediating variable, intermediary variable, or intervening variable) ; direct versus indirect effects, total effects (interpretation: "The direct effect measures the extent to which the dependent variable changes when the independent variable increases by one unit and the mediator variable remains unaltered. In contrast, the indirect effect measures the extent to which the dependent variable changes when the independent variable is held fixed and the mediator variable changes by the amount it would have changed had the independent variable increased by one unit.") ; the size of indirect effects: use standardized regression coefficients (multiply for indirect effect = completely standardized indirect effect in PROCESS) and usual rules of thumb (and note that a product of proportions tends towards zero) ; full and partial mediation ; the sign of direct and indirect effects, (partly) spurious and suppressed effects/ confounding and supression - see Davis' booklet}

## Path Model with Regression Analysis
{assumed causal order of variables ; multiple regression for each 'outcome' (endogenous variable) with all causally prior variables ; calculation and interpretation of indirect and total effects ; no significance test for indirect effects (in SPSS) ; assumptions (as in multiple regression?)}

## Statistical Inference for Indirect Effects
{bootstrapping sampling distributions for indirect effects (usual conditions for bootstrapping: not too small a sample that is representative) ; using the PROCESS macro and the most common mediation models ; possibility to combine mediation and moderation with other PROCESS models (requires additional explanation of types of moderators that can be used and the meaning of statistical tests - different estimates for different groups?)}

## Reporting Mediation Results
{[See @RefWorks:3873: 198-202] ; general rules same as for reporting regression analyses ; include indirect effects and their statistical significance and confidence intervals ; report number of bootstrap samples and the method used for the confidence intervals (by default, use accelerated) ; report numeric results in a table rather than in the text ; preferably, report a statisical diagram with unstandardized effect sizes to the arcs (direct effects)}

## Controlling for Effects of Other Predictors
{the multiple regression model assumes correlations among predictors ; effect of one predictor is corrected for indirect effects of other predictors, so unique effect ; this is meant by "controlling for"}

## Criticisms of Mediation
{causal order assumed: is it plausible (time order)?, causality assumed, not proven ; are the mediator and the outcome (and predictor) conceptually/theoretically different? ; controlling for the mediator is not the same as keeping the mediator value the same (for varying values of the predictor), which is the definition of the direct effect; the mediator is supposed to change due to changes in the predictor (causal effect) but we only select the cases where the mediator has a particular value [see @RefWorks:3938]}